### ISSUE TITLE
Cannot access initial arguments

### ISSUE THREAD

**Issue by ainth** [git-hooks/git-hooks#15]
I am working on the following: https://gist.github.com/ainth/9cb2ae4270136aa9f7c7

I need to know if the user is trying to force push so I need the arguments given to `git push` (in particular `git push -f`). How can I access these when using git-hooks?

`ps -ocommand= -p $PPID` works in a plain `pre-push` hook but not when the hook is executed with `git-hooks`.

**Comment by CatTail** [comment]
`ps -ocommand= -p $PPID` don't work on git-hooks because `ps -ocommand= -p $PPID` get current process command which is `git-hooks run XXX`.

There doesn't seemed to have a nice way to fix this.

I sugguest you do force push detection in server side with pre-receive, by check the last commit rather than `-f` argument.
